name: Lint

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: yarn

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
          yarn build:package

      - name: Lint
        run: |
          yarn format-check
          yarn typecheck
          yarn lint
          yarn spellcheck
